#!/bin/sh
# Run the template case on its own: the same sequence the database runner uses.
cd "${0%/*}" || exit 1

rm -rf 0 && cp -r 0.orig 0
blockMesh  > log.blockMesh  2>&1 || exit 1
checkMesh  > log.checkMesh  2>&1 || exit 1
setFields  > log.setFields  2>&1 || exit 1
interFoam  > log.interFoam  2>&1
